use dibbuk::debugger::queue::CommandQueue;
use dibbuk::gdb::{self, process::GdbHandle};
use dibbuk::il::{DebuggerCommand, DebuggerEvent};
use tokio::sync::broadcast;

struct TestApp {
    debugger_state: CommandQueue,
    stdout: broadcast::Receiver<String>,
    running: bool,
}

impl TestApp {
    pub fn new(gdb_handle: &GdbHandle) -> Self {
        TestApp {
            debugger_state: CommandQueue::new(gdb_handle.stdin_tx.clone()),
            stdout: gdb_handle.subscribe_stdout(),
            running: false,
        }
    }

    pub async fn run(mut self) {
        self.running = true;
        self.debugger_state
            .queue(&DebuggerCommand::Raw("help".into()));
        self.debugger_state
            .queue(&DebuggerCommand::Raw("asd;flkajsdf".into()));

        while self.running {
            // succeeds when a single thing generated by gdb is parsed and lifted correctly
            if self.handle_stdout_event().await {
                break;
            }
        }
    }

    async fn handle_stdout_event(&mut self) -> bool {
        tokio::select! {
            line = self.stdout.recv() => {
                if let Ok(line) = line &&
                let Ok(evt) = self.debugger_state.lift(gdb::mi::parse(line.as_str()).unwrap()) {
                    println!("EVENT: {:?} -> {:?}", &line, &evt);
                    self.debugger_state.update(&evt);
                    true
                } else {

                    false
                }
            }
            _ = tokio::time::sleep(tokio::time::Duration::from_millis(20)) => {
                    self.debugger_state.update(&DebuggerEvent::Tick);
                    false
            }
        }
    }
}

#[tokio::test]
async fn simple_main() {
    let gdb_handle = gdb::Builder::new().spawn().unwrap();
    let app = TestApp::new(&gdb_handle);
    app.run().await;
    // let app = TestApp::new();
}
